name: Django CI

on:
  pull_request:
  push:
    branches: ["develop"]
  

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        # FIXME: Revert to '3.8' once Python is fixed:
        # https://bugs.python.org/issue44061
        python-version: '3.8.9'
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        pytest
